grails-app/domain/proyecto/base/security/UsuarioSistema.groovy
package proyecto.base.security



class UsuarioSistema {

    transient springSecurityService
	transient String captcha

    // Datos del usuario
    String nombre
    String apellidoPaterno
    String apellidoMaterno
    String username
    String password
	Boolean enabled
	Boolean accountExpired
	Boolean accountLocked
	Boolean passwordExpired

    String tipoUsuario

    Integer usuarioModifica
	Integer estadoLogico
	Date dateCreated
	Date lastUpdated



	static constraints = {
		username (email:true, blank:false, unique:true, maxSize:60)
		password (blank:false, maxSize:50)
        tipoUsuario nullable: true, blank:true
        nombre  (blank:false, maxSize:60)
        apellidoPaterno  (blank:false, maxSize:60)
        apellidoMaterno  (blank:false, maxSize:60)
		enabled (nullable:false)
		usuarioModifica(nullable:true)
		estadoLogico(nullable :true)
        captcha(nullable:true)
	}


	Set<Permiso> getAuthorities() {
		UsuarioSistemaPermiso.findAllByUsuarioSistema(this).collect { it.permiso } as Set
	}

	def beforeInsert() {
		encodePassword()
		estadoLogico = 1
	}

	def beforeUpdate() {
		if (isDirty('password')) {
			encodePassword()
		}
	}

	protected void encodePassword() {
		password = springSecurityService.encodePassword(password)
	}

    static mapping = {
        datasource 'ALL'
    }

    String toString(){
        "$nombre ${apellidoPaterno?:''} ${apellidoMaterno?:''}"
    }
}

grails-app/views/usuarioSistema/_activarUsuario.gsp
<script type="text/javascript">
    $(document).ready(function () {

        $('#spinner').bind("ajaxSend", function() {
            $(this).show();
            $('#content-modal').hide();
        }).bind("ajaxComplete", function() {
            $(this).hide();
            $('#content-modal').show();
        });

    });

    $('[data-load-remote]').on('click',function(e) {
        e.preventDefault();
        var $this = $(this);
        var remote = $this.data('load-remote');
        if(remote) {
            $($this.data('remote-target')).load(remote);
        }
    });
</script>

<div id="modalActivarUsuario" class="modal hide fade" tabindex="-1" role="dialog">
    <div class="modal-header">
        <a class="close" data-dismiss="modal">×</a>
        <h3>Asignar rol</h3>
    </div>
    <g:form class="form-horizontal" controller="solicitudCuenta">
    <g:render template="/common/loading"/>
    <div id="content-modal" class="modal-body">

    </div>
    <div class="modal-footer">
        <a href="#" class="btn" data-dismiss="modal" aria-hidden="true">Close</a>
        <g:actionSubmit value="Guardar" class="btn btn-primary" action="asignarRol"/>

    </div>
    </g:form>
</div>

grails-app/views/usuarioSistema/_asignarRol.gsp
<%@ page import="proyecto.base.security.UsuarioSistema" %>
<%@ page import="proyecto.base.security.Permiso" %>

<g:hiddenField name="id" value="${usuarioSistemaInstance.id}"/>

<div class="fieldcontain ${hasErrors(bean: usuarioSistemaInstance, field: 'username', 'error')} required">
    <div class="control-group">
        <label class="control-label" for="username">
            <g:message code="usuarioSistema.username.label" default="Username" />

        </label>
        <div class="controls">
            ${fieldValue(bean: usuarioSistemaInstance, field: "username")}
        </div>
    </div>
</div>


<div class="fieldcontain ${hasErrors(bean: usuarioSistemaInstance, field: 'nombre', 'error')} required">
    <div class="control-group">
        <label class="control-label" for="nombre">
            <g:message code="usuarioSistema.nombre.label" default="Nombre" />

        </label>
        <div class="controls">
            ${usuarioSistemaInstance}
        </div>
    </div>
</div>

<div class="required">
    <div class="control-group">
        <label class="control-label" for="rol">
            <g:message code="usuarioSistema.rol.label" default="Rol" />
            <span class="required-indicator">*</span>
        </label>
        <div class="controls">
            <g:select name="rol" from="${Permiso.list()}"
                optionKey="id"
                noSelection="['':'-- Seleccione rol --']" />
        </div>
    </div>
</div>

grails-app/views/usuarioSistema/_form.gsp
<%@ page import="proyecto.base.security.UsuarioSistema" %>



<div class="fieldcontain ${hasErrors(bean: usuarioSistemaInstance, field: 'username', 'error')} required">
    <div class="control-group">
        <label class="control-label" for="username">
		<g:message code="usuarioSistema.username.label" default="Username" />
		<span class="required-indicator">*</span>
	</label>
        <div class="controls">
	        <g:field type="email" name="username" placeholder="username" class="input-large" maxlength="60" required="" value="${usuarioSistemaInstance?.username}"/>
        </div>
    </div>
</div>


<div class="fieldcontain ${hasErrors(bean: usuarioSistemaInstance, field: 'tipoUsuario', 'error')} ">
    <div class="control-group">
        <label class="control-label" for="tipoUsuario">
		<g:message code="usuarioSistema.tipoUsuario.label" default="Tipo Usuario" />
		
	</label>
        <div class="controls">
	        <g:textField  name="tipoUsuario" placeholder="tipoUsuario" class="input-large" value="${usuarioSistemaInstance?.tipoUsuario}"/>
        </div>
    </div>
</div>

<div class="fieldcontain ${hasErrors(bean: usuarioSistemaInstance, field: 'nombre', 'error')} required">
    <div class="control-group">
        <label class="control-label" for="nombre">
		<g:message code="usuarioSistema.nombre.label" default="Nombre" />
		<span class="required-indicator">*</span>
	</label>
        <div class="controls">
	        <g:textField  name="nombre" placeholder="nombre" class="input-large" maxlength="60" required="" value="${usuarioSistemaInstance?.nombre}"/>
        </div>
    </div>
</div>

<div class="fieldcontain ${hasErrors(bean: usuarioSistemaInstance, field: 'apellidoPaterno', 'error')} required">
    <div class="control-group">
        <label class="control-label" for="apellidoPaterno">
		<g:message code="usuarioSistema.apellidoPaterno.label" default="Apellido Paterno" />
		<span class="required-indicator">*</span>
	</label>
        <div class="controls">
	        <g:textField  name="apellidoPaterno" placeholder="apellidoPaterno" class="input-large" maxlength="60" required="" value="${usuarioSistemaInstance?.apellidoPaterno}"/>
        </div>
    </div>
</div>

<div class="fieldcontain ${hasErrors(bean: usuarioSistemaInstance, field: 'apellidoMaterno', 'error')} required">
    <div class="control-group">
        <label class="control-label" for="apellidoMaterno">
		<g:message code="usuarioSistema.apellidoMaterno.label" default="Apellido Materno" />
		<span class="required-indicator">*</span>
	</label>
        <div class="controls">
	        <g:textField  name="apellidoMaterno" placeholder="apellidoMaterno" class="input-large" maxlength="60" required="" value="${usuarioSistemaInstance?.apellidoMaterno}"/>
        </div>
    </div>
</div>

<div class="fieldcontain ${hasErrors(bean: usuarioSistemaInstance, field: 'enabled', 'error')} ">
    <div class="control-group">
        <label class="control-label" for="enabled">
		<g:message code="usuarioSistema.enabled.label" default="Enabled" />
		
	</label>
        <div class="controls">
	        <g:checkBox name="enabled" value="${usuarioSistemaInstance?.enabled}" />
        </div>
    </div>
</div>

grails-app/views/usuarioSistema/create.gsp
<%@ page import="proyecto.base.security.UsuarioSistema" %>
<!doctype html>
<html>
	<head>
		<meta name="layout" content="bootstrap_fluid">
		<g:set var="entityName" value="${message(code: 'usuarioSistema.label', default: 'UsuarioSistema')}" />
		<title><g:message code="default.create.label" args="[entityName]" /></title>
	</head>
	<body>

    <div class="row-fluid">
        <div class="span3">
            <div class="well sidebar-nav">
                <ul class="nav nav-list">
                    <li class="nav-header"><g:message code="default.actions.label" default="Acciones" /></li>
				    <li>
                        <g:link action="list">
                            <i class="icon-th-list"></i><g:message code="default.list.label" args="[entityName]" />
                        </g:link>
                    </li>
			    </ul>
            </div>
		</div>

		<div id="create-usuarioSistema" class="span9" role="main">
			<h1><g:message code="default.create.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			    <div class="alert alert-success" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${usuarioSistemaInstance}">
                <div class="alert alert-error">
                    <ul class="unstyled" role="alert">
                        <g:eachError bean="${usuarioSistemaInstance}" var="error">
                        <li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
                        </g:eachError>
                    </ul>
                </div>
			</g:hasErrors>
			<g:form class="form-horizontal" action="save" >
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:submitButton name="create" class="btn btn-primary" value="${message(code: 'default.button.create.label', default: 'Create')}" />
				</fieldset>
			</g:form>
		</div>
    </div>
	</body>
</html>

grails-app/views/usuarioSistema/edit.gsp
<%@ page import="proyecto.base.security.UsuarioSistema" %>
<!doctype html>
<html>
	<head>
		<meta name="layout" content="bootstrap_fluid">
		<g:set var="entityName" value="${message(code: 'usuarioSistema.label', default: 'UsuarioSistema')}" />
		<title><g:message code="default.edit.label" args="[entityName]" /></title>
	</head>
	<body>

    <div class="row-fluid">
        <div class="span3">
            <div class="well sidebar-nav">
                <ul class="nav nav-list">
                    <li class="nav-header"><g:message code="default.actions.label" default="Acciones" /></li>
                    <li><g:link action="list">
                        <i class="icon-th-list"></i><g:message code="default.list.label" args="[entityName]" /></g:link></li>
                    <li><g:link action="create">
                        <i class="icon-plus"></i><g:message code="default.new.label" args="[entityName]" /></g:link></li>
                </ul>
            </div>
		</div>
		<div id="edit-usuarioSistema" class="span9" role="main">
			<h1><g:message code="default.edit.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="alert alert-success" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${usuarioSistemaInstance}">
                <div class="alert alert-error">
                    <ul class="unstyled" role="alert">
                        <g:eachError bean="${usuarioSistemaInstance}" var="error">
                            <li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
                        </g:eachError>
                    </ul>
                </div>
			</g:hasErrors>
			<g:form class="form-horizontal" method="post" >
				<g:hiddenField name="id" value="${usuarioSistemaInstance?.id}" />
				<g:hiddenField name="version" value="${usuarioSistemaInstance?.version}" />
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:actionSubmit class="btn btn-primary" action="update" value="${message(code: 'default.button.update.label', default: 'Update')}" />
					<g:actionSubmit class="btn" action="delete" value="${message(code: 'default.button.delete.label', default: 'Delete')}" formnovalidate="" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
				</fieldset>
			</g:form>
		</div>
        </div>
	</body>
</html>

grails-app/views/usuarioSistema/list.gsp
<%@ page import="proyecto.base.security.UsuarioSistema" %>
<!doctype html>
<html>
	<head>
		<meta name="layout" content="bootstrap_fluid">
		<g:set var="entityName" value="${message(code: 'usuarioSistema.label', default: 'UsuarioSistema')}" />
		<title><g:message code="default.list.label" args="[entityName]" /></title>
	</head>
	<body>
		<div class="row-fluid">
            <div class="span3">
                <div class="well sidebar-nav">
                    <ul class="nav nav-list">
                        <li class="nav-header"><g:message code="default.actions.label" default="Acciones" /></li>
                        <li><g:link class="create" action="create">
                            <i class="icon-plus"></i><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			        </ul>
                </div>
            </div>


		<div id="list-usuarioSistema" class="span9" role="main">
			<h1><g:message code="default.list.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="alert alert-success" role="status">${flash.message}</div>
			</g:if>
			<table class="table table-hover">
				<thead>
					<tr>
					
						<g:sortableColumn property="username" title="${message(code: 'usuarioSistema.username.label', default: 'Username')}" />
					
						<g:sortableColumn property="password" title="${message(code: 'usuarioSistema.password.label', default: 'Password')}" />
					
						<g:sortableColumn property="tipoUsuario" title="${message(code: 'usuarioSistema.tipoUsuario.label', default: 'Tipo Usuario')}" />
					
						<g:sortableColumn property="nombre" title="${message(code: 'usuarioSistema.nombre.label', default: 'Nombre')}" />
					
						<g:sortableColumn property="apellidoPaterno" title="${message(code: 'usuarioSistema.apellidoPaterno.label', default: 'Apellido Paterno')}" />
					
						<g:sortableColumn property="apellidoMaterno" title="${message(code: 'usuarioSistema.apellidoMaterno.label', default: 'Apellido Materno')}" />
					
                        <th class="sortable" width="10px">Acciones</th>
					</tr>
				</thead>
				<tbody>
				<g:each in="${usuarioSistemaInstanceList}" status="i" var="usuarioSistemaInstance">
					<tr class="${(i % 2) == 0 ? 'even' : 'odd'}">
					
						<td><g:link action="show" id="${usuarioSistemaInstance.id}">${fieldValue(bean: usuarioSistemaInstance, field: "username")}</g:link></td>
					
						<td>${fieldValue(bean: usuarioSistemaInstance, field: "password")}</td>
					
						<td>${fieldValue(bean: usuarioSistemaInstance, field: "tipoUsuario")}</td>
					
						<td>${fieldValue(bean: usuarioSistemaInstance, field: "nombre")}</td>
					
						<td>${fieldValue(bean: usuarioSistemaInstance, field: "apellidoPaterno")}</td>
					
						<td>${fieldValue(bean: usuarioSistemaInstance, field: "apellidoMaterno")}</td>
					
                        <td><!-- Icons -->
                            <g:form>
                                <g:hiddenField name="id" value="${usuarioSistemaInstance.id}"/>
                                <g:actionSubmitImage class="table-button" value="${message(code: 'global.edit.label', default: 'Editar')}" src="${resource(dir: 'images/icons', file: 'pencil.png')}" action="edit" formnovalidate=""/>
                                <g:actionSubmitImage class="table-button" value="${message(code: 'global.delete.label', default: 'Eliminar')}" src="${resource(dir: 'images/icons', file: 'cross.png')}" action="delete" formnovalidate="" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');"/>
                            </g:form>
                        </td>
					</tr>
				</g:each>
				</tbody>
			</table>

			<g:paginate total="${usuarioSistemaInstanceTotal}" />

		</div>
        </div>
	</body>
</html>

grails-app/views/usuarioSistema/show.gsp
<%@ page import="proyecto.base.security.UsuarioSistema" %>
<!doctype html>
<html>
	<head>
		<meta name="layout" content="bootstrap_fluid">
		<g:set var="entityName" value="${message(code: 'usuarioSistema.label', default: 'UsuarioSistema')}" />
		<title><g:message code="default.show.label" args="[entityName]" /></title>
	</head>
	<body>

    <div class="row-fluid">
        <div class="span3">
            <div class="well sidebar-nav">
                <ul class="nav nav-list">
                    <li class="nav-header"><g:message code="default.actions.label" default="Acciones" /></li>
				<li><g:link class="list" action="list">
                    <i class="icon-th-list"></i><g:message code="default.list.label" args="[entityName]" /></g:link>
                </li>
				<li><g:link class="create" action="create">
                    <i class="icon-plus"></i><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
                </div>
		</div>
		<div id="show-usuarioSistema" class="span9" role="main">
			<h1><g:message code="default.show.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="alert alert-success" role="status">${flash.message}</div>
			</g:if>
			<ol class="property-list usuarioSistema">
			
				<g:if test="${usuarioSistemaInstance?.username}">
				<li class="fieldcontain">
					<span id="username-label" class="property-label"><g:message code="usuarioSistema.username.label" default="Username" /></span>
					
						<span class="property-value" aria-labelledby="username-label"><g:fieldValue bean="${usuarioSistemaInstance}" field="username"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${usuarioSistemaInstance?.password}">
				<li class="fieldcontain">
					<span id="password-label" class="property-label"><g:message code="usuarioSistema.password.label" default="Password" /></span>
					
						<span class="property-value" aria-labelledby="password-label"><g:fieldValue bean="${usuarioSistemaInstance}" field="password"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${usuarioSistemaInstance?.tipoUsuario}">
				<li class="fieldcontain">
					<span id="tipoUsuario-label" class="property-label"><g:message code="usuarioSistema.tipoUsuario.label" default="Tipo Usuario" /></span>
					
						<span class="property-value" aria-labelledby="tipoUsuario-label"><g:fieldValue bean="${usuarioSistemaInstance}" field="tipoUsuario"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${usuarioSistemaInstance?.nombre}">
				<li class="fieldcontain">
					<span id="nombre-label" class="property-label"><g:message code="usuarioSistema.nombre.label" default="Nombre" /></span>
					
						<span class="property-value" aria-labelledby="nombre-label"><g:fieldValue bean="${usuarioSistemaInstance}" field="nombre"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${usuarioSistemaInstance?.apellidoPaterno}">
				<li class="fieldcontain">
					<span id="apellidoPaterno-label" class="property-label"><g:message code="usuarioSistema.apellidoPaterno.label" default="Apellido Paterno" /></span>
					
						<span class="property-value" aria-labelledby="apellidoPaterno-label"><g:fieldValue bean="${usuarioSistemaInstance}" field="apellidoPaterno"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${usuarioSistemaInstance?.apellidoMaterno}">
				<li class="fieldcontain">
					<span id="apellidoMaterno-label" class="property-label"><g:message code="usuarioSistema.apellidoMaterno.label" default="Apellido Materno" /></span>
					
						<span class="property-value" aria-labelledby="apellidoMaterno-label"><g:fieldValue bean="${usuarioSistemaInstance}" field="apellidoMaterno"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${usuarioSistemaInstance?.enabled}">
				<li class="fieldcontain">
					<span id="enabled-label" class="property-label"><g:message code="usuarioSistema.enabled.label" default="Enabled" /></span>
					
						<span class="property-value" aria-labelledby="enabled-label"><g:formatBoolean boolean="${usuarioSistemaInstance?.enabled}" /></span>
					
				</li>
				</g:if>
			
				<g:if test="${usuarioSistemaInstance?.usuarioModifica}">
				<li class="fieldcontain">
					<span id="usuarioModifica-label" class="property-label"><g:message code="usuarioSistema.usuarioModifica.label" default="Usuario Modifica" /></span>
					
						<span class="property-value" aria-labelledby="usuarioModifica-label"><g:fieldValue bean="${usuarioSistemaInstance}" field="usuarioModifica"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${usuarioSistemaInstance?.estadoLogico}">
				<li class="fieldcontain">
					<span id="estadoLogico-label" class="property-label"><g:message code="usuarioSistema.estadoLogico.label" default="Estado Logico" /></span>
					
						<span class="property-value" aria-labelledby="estadoLogico-label"><g:fieldValue bean="${usuarioSistemaInstance}" field="estadoLogico"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${usuarioSistemaInstance?.captcha}">
				<li class="fieldcontain">
					<span id="captcha-label" class="property-label"><g:message code="usuarioSistema.captcha.label" default="Captcha" /></span>
					
						<span class="property-value" aria-labelledby="captcha-label"><g:fieldValue bean="${usuarioSistemaInstance}" field="captcha"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${usuarioSistemaInstance?.accountExpired}">
				<li class="fieldcontain">
					<span id="accountExpired-label" class="property-label"><g:message code="usuarioSistema.accountExpired.label" default="Account Expired" /></span>
					
						<span class="property-value" aria-labelledby="accountExpired-label"><g:formatBoolean boolean="${usuarioSistemaInstance?.accountExpired}" /></span>
					
				</li>
				</g:if>
			
				<g:if test="${usuarioSistemaInstance?.accountLocked}">
				<li class="fieldcontain">
					<span id="accountLocked-label" class="property-label"><g:message code="usuarioSistema.accountLocked.label" default="Account Locked" /></span>
					
						<span class="property-value" aria-labelledby="accountLocked-label"><g:formatBoolean boolean="${usuarioSistemaInstance?.accountLocked}" /></span>
					
				</li>
				</g:if>
			
				<g:if test="${usuarioSistemaInstance?.passwordExpired}">
				<li class="fieldcontain">
					<span id="passwordExpired-label" class="property-label"><g:message code="usuarioSistema.passwordExpired.label" default="Password Expired" /></span>
					
						<span class="property-value" aria-labelledby="passwordExpired-label"><g:formatBoolean boolean="${usuarioSistemaInstance?.passwordExpired}" /></span>
					
				</li>
				</g:if>
			
			</ol>
			<g:form>
				<fieldset class="buttons">
					<g:hiddenField name="id" value="${usuarioSistemaInstance?.id}" />
					<g:link class="btn btn-primary" action="edit" id="${usuarioSistemaInstance?.id}"><g:message code="default.button.edit.label" default="Edit" /></g:link>
					<g:actionSubmit class="btn" action="delete" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
				</fieldset>
			</g:form>
		</div>
        </div>
	</body>
</html>